version: '3.1'

services:

  db:
    image: postgres:${POSTGRESQL_VERSION}
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgresql-volume:/var/lib/postgresql/data/pgdata:Z
    # volumes:
    #   - "./.data/db:/var/lib/postgresql/data/pgdata"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      ADMINER_DESIGN: bueltge
      # ADMINER_DESIGN: rmsoft_blue

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ".backups:/var/lib/pgadmin/storage/odoo"

  # odoo:
  #   image: odoo:11
  #   depends_on:
  #     - db
  #   ports:
  #     - "8069:8069"
  #   environment:
  #     HOST: db
  #     USER: ${POSTGRES_USER}
  #     PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgresql-volume:
    external: true